# Generated by Django 5.1.5 on 2025-01-26 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment_booking", "0002_appointmentmodel_is_canceled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentmodel",
            name="reserved_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
